"""initial schema

Revision ID: 03ba4fe7b911
Revises: 
Create Date: 2026-09-25 18:44:38.256486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '03ba4fe7b911'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('llm_model', sa.String(length=80), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('voice_id', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('max_call_seconds', sa.Integer(), nullable=False),
    sa.Column('workflow', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('name', name=op.f('uq_agents_name'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_created_at'), ['created_at'], unique=False)

    op.create_table('calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('to_number', sa.String(length=32), nullable=False),
    sa.Column('from_number', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('queued', 'scheduled', 'dialing', 'in_progress', 'completed', 'failed', 'retrying', 'canceled', name='ck_callstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('priority', sa.Enum('urgent', 'high', 'normal', 'low', name='ck_callpriority', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('outcome', sa.Enum('resolved', 'escalated', 'callback_scheduled', 'no_answer', 'voicemail', 'customer_hung_up', 'unresolved', name='ck_calloutcome', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('collected_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('failure_category', sa.Enum('network', 'provider_error', 'rate_limited', 'timeout', 'no_answer', 'busy', 'invalid_number', 'do_not_call', 'agent_config', 'canceled', 'expired', 'unknown', name='ck_failurecategory', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.String(length=512), nullable=True),
    sa.Column('cost_cents', sa.Float(), nullable=False),
    sa.Column('call_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_calls_agent_id_agents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls')),
    sa.UniqueConstraint('idempotency_key', name='uq_calls_idempotency_key')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index('ix_calls_agent_created', ['agent_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_failure_category'), ['failure_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_status'), ['status'], unique=False)
        batch_op.create_index('ix_calls_status_scheduled_at', ['status', 'scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_to_number'), ['to_number'], unique=False)

    op.create_table('call_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('enqueued', 'claimed', 'dialing', 'answered', 'turn', 'node_entered', 'transferred', 'completed', 'failed', 'retry_scheduled', 'dead_lettered', 'canceled', 'throttled', 'deferred', name='ck_eventtype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_events_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_events'))
    )
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_events_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_events_type'), ['type'], unique=False)

    op.create_table('call_turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('agent', 'customer', 'system', name='ck_turnrole', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('stt_ms', sa.Float(), nullable=True),
    sa.Column('llm_ms', sa.Float(), nullable=True),
    sa.Column('tts_ms', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_turns_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_turns')),
    sa.UniqueConstraint('call_id', 'index', name='uq_call_turns_call_id')
    )
    with op.batch_alter_table('call_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_turns_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_turns_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_turns_created_at'))
        batch_op.drop_index(batch_op.f('ix_call_turns_call_id'))

    op.drop_table('call_turns')
    with op.batch_alter_table('call_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_events_type'))
        batch_op.drop_index(batch_op.f('ix_call_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_call_events_call_id'))

    op.drop_table('call_events')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_to_number'))
        batch_op.drop_index('ix_calls_status_scheduled_at')
        batch_op.drop_index(batch_op.f('ix_calls_status'))
        batch_op.drop_index(batch_op.f('ix_calls_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_calls_priority'))
        batch_op.drop_index(batch_op.f('ix_calls_outcome'))
        batch_op.drop_index(batch_op.f('ix_calls_failure_category'))
        batch_op.drop_index(batch_op.f('ix_calls_external_id'))
        batch_op.drop_index(batch_op.f('ix_calls_created_at'))
        batch_op.drop_index(batch_op.f('ix_calls_agent_id'))
        batch_op.drop_index('ix_calls_agent_created')

    op.drop_table('calls')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_created_at'))

    op.drop_table('agents')
    # ### end Alembic commands ###
